on: push
jobs:
 commit-message-check:
   runs-on: ubuntu-latest
   steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: 1512508325
          body: |
            **Edit:** Some additional info
          reactions: eyes
